site_name: Redbrick Docs
site_url: https://docs.redbrick.dcu.ie/
repo_url: https://github.com/redbrick/docs
repo_name: redbrick/docs
use_directory_urls: true

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tracking
    - navigation.indexes

plugins:
  - awesome-pages
  - search
  - git-revision-date-localized:
      type: timeago

markdown_extensions:
  - attr_list
  - abbr
  - admonition
  - pymdownx.snippets
  - pymdownx.tabbed
  - pymdownx.superfences

extra:
  github_org: https://github.com/redbrick
