site_name: Redbrick Docs
site_description: Redbrick Technical Documentation
site_url: https://docs.redbrick.dcu.ie/

repo_name: Redbrick/docs
repo_url: https://github.com/redbrick/docs

theme:
  logo: assets/logo.png
  favicon: assets/favicon.png
  name: material
  custom_dir: docs/overrides
  features:
    - navigation.sections
    - navigation.tabs
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: black
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: black
      accent: red
      toggle:
        icon: material/weather-night
        name: Switch to light mode

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Redbrick/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/redbrickdcu?lang=en
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/c/redbrickdcusnetworkingsociety

markdown_extensions:
  - toc:
      permalink: true
  - attr_list
  - codehilite:
      guess_lang: true
  - pymdownx.critic
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - pymdownx.details

nav:
  - Home: index.md
  - Services:
    - services/index.md
    - Servers: services/servers.md
    - Bind9: services/bind.md
    - CodiMD: services/codimd.md
    - Gitea: services/gitea.md
    - Icecast: services/icecast.md
    - IRC: services/irc.md
    - NFS: services/nfs.md
    - ZnapZend: services/znapzend.md
  - cheatsheet.md
  - api.md
  - roadmap.md
  - Aperture:
      - aperture/index.md
      - Images: aperture/images.md